let stockProductos = [
    {id: 1, nombre: "Tenis Nike", tipo:"Casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "1200", talle:"24/25", img:"/img/productos/1.jpg" },
    {id: 2, nombre: "Tenis Nike", tipo:"Casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "1200", talle:"24/25", img:"/img/productos/2.jpg" },
    {id: 3, nombre: "Tenis Nike", tipo:"Casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "1730", talle:"26/27", img:"/img/productos/3.jpg" },
    {id: 4, nombre: "Tenis Nike", tipo:"casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "1200", talle:"25/26/27/28", img:"/img/productos/4.jpg" },
    {id: 5, nombre: "Tenis Nike", tipo:"casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "1970", talle:"24/25/26", img:"/img/productos/5.jpg" },
    {id: 6, nombre: "Tenis Nike", tipo:"casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "2330", talle:"24/25/26", img:"/img/productos/6.jpg" },
    {id: 7, nombre: "Tenis Nike", tipo:"casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "2560", talle:"23/24/25", img:"/img/productos/7.jpg" },
    {id: 8, nombre: "Tenis Nike", tipo:"casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "3200", talle:"25/26", img:"/img/productos/8.jpg" },
    {id: 9, nombre: "Tenis Nike", tipo:"casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "2200", talle:"24/26", img:"/img/productos/9.jpg" },
    {id: 10, nombre: "Tenis Nike", tipo:"casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "3200", talle:"27/28", img:"/img/productos/10.jpg" },
    {id: 11, nombre: "Tenis Nike", tipo:"casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "3000", talle:"24/22", img:"/img/productos/11.jpg" },
    {id: 12, nombre: "Tenis Nike", tipo:"casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "299", talle:"24/25/26/28", img:"/img/productos/12.jpg" },
    {id: 13, nombre: "Tenis Nike", tipo:"casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "1350", talle:"24/25/28", img:"/img/productos/13.jpg" },
    {id: 14, nombre: "Tenis Nike", tipo:"casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "2700", talle:"23/25/26/27", img:"/img/productos/14.jpg" },
    {id: 15, nombre: "Tenis Nike", tipo:"casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "1200", talle:"24/25", img:"/img/productos/15.jpg" },
    {id: 16, nombre: "Tenis Nike", tipo:"casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "1340", talle:"24/25/26", img:"/img/productos/16.jpg" },
    {id: 17, nombre: "Tenis Nike", tipo:"casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "1800", talle:"23/24/25", img:"/img/productos/17.jpg" },
    {id: 18, nombre: "Tenis Nike", tipo:"casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "1790", talle:"22/23", img:"/img/productos/18.jpg" },
    {id: 19, nombre: "Tenis Nike", tipo:"casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "1999", talle:"24/25/26/27/28", img:"/img/productos/19.jpg" },
    {id: 20, nombre: "Tenis Nike", tipo:"casual", cantidad:"1", desc:"¡Nuevos lanzamientos!", precio: "2050", talle:"24/27/28", img:"/img/productos/20.jpg" },
]